// -------------------------------------------------------------------------------------------------
//  Copyright (C) 2015-2025 Nautech Systems Pty Ltd. All rights reserved.
//  https://nautechsystems.io
//
//  Licensed under the GNU Lesser General Public License Version 3.0 (the "License");
//  You may not use this file except in compliance with the License.
//  You may obtain a copy of the License at https://www.gnu.org/licenses/lgpl-3.0.en.html
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
// -------------------------------------------------------------------------------------------------

//! Synthetic order ID generator for L3 reconstruction.
//!
//! Generates deterministic, unique order IDs for synthetic orders created during L3
//! orderbook reconstruction from L2 data. The generator uses fast hashing (ahash) to
//! create collision-resistant identifiers from order characteristics.
//!
//! # Design
//!
//! The order ID is generated by hashing a combination of:
//! - Instrument ID
//! - Order side (Buy/Sell)
//! - Price level
//! - Timestamp
//! - Sequence number
//!
//! This approach ensures:
//! - **Determinism**: Same inputs always produce the same ID
//! - **Uniqueness**: Different orders produce different IDs
//! - **Performance**: Fast hashing enables millions of IDs per second
//! - **Collision Resistance**: 64-bit hash space minimizes collisions

use std::hash::{Hash, Hasher};

use ahash::AHasher;
use nautilus_core::nanos::UnixNanos;
use nautilus_model::{enums::OrderSide, identifiers::VenueOrderId, types::Price};

/// Generates deterministic synthetic order IDs for L3 reconstruction.
///
/// # Purpose
///
/// When reconstructing L3 orderbook state from L2 market data, exchanges don't provide
/// actual order IDs since L2 data only contains aggregated price levels. This generator
/// creates synthetic order IDs that are:
///
/// - Deterministic: Same order characteristics produce the same ID
/// - Unique: Different orders produce different IDs with high probability
/// - Fast: Uses ahash for high-throughput generation
///
/// # Example
///
/// ```rust
/// use nautilus_l3_engine::order_id::SyntheticOrderIdGenerator;
/// use nautilus_model::{enums::OrderSide, types::Price};
/// use nautilus_core::nanos::UnixNanos;
///
/// let mut generator = SyntheticOrderIdGenerator::new();
///
/// let order_id = generator.generate_id(
///     "BTCUSDT",
///     OrderSide::Buy,
///     Price::from("50000.00"),
///     UnixNanos::from(1700000000000000000),
///     42,
/// );
/// ```
pub struct SyntheticOrderIdGenerator;

impl SyntheticOrderIdGenerator {
    /// Creates a new [`SyntheticOrderIdGenerator`] instance.
    #[must_use]
    pub fn new() -> Self {
        Self
    }

    /// Generates a deterministic synthetic order ID.
    ///
    /// # Arguments
    ///
    /// * `instrument_id` - The instrument identifier (e.g., "BTCUSDT")
    /// * `side` - The order side (Buy or Sell)
    /// * `price` - The order price level
    /// * `timestamp` - The timestamp when the order was observed
    /// * `sequence` - The exchange sequence number for this update
    ///
    /// # Returns
    ///
    /// A unique [`VenueOrderId`] representing the synthetic order.
    ///
    /// # Determinism
    ///
    /// The same combination of inputs will always produce the same order ID. This is
    /// critical for idempotent processing of market data replays and backtesting.
    ///
    /// # Performance
    ///
    /// Uses ahash for fast, non-cryptographic hashing. Suitable for generating millions
    /// of order IDs per second.
    #[must_use]
    pub fn generate_id(
        &mut self,
        instrument_id: &str,
        side: OrderSide,
        price: Price,
        timestamp: UnixNanos,
        sequence: u64,
    ) -> VenueOrderId {
        let hash = Self::hash_order_key(instrument_id, side, price, timestamp, sequence);

        // Format as hex string with prefix to indicate synthetic origin
        // Format: L3-{instrument_short}-{hash_hex}
        let instrument_short = instrument_id.chars().take(8).collect::<String>();

        let id_string = format!("L3-{}-{:016x}", instrument_short, hash);

        VenueOrderId::new(id_string)
    }

    /// Computes a deterministic 64-bit hash from order characteristics.
    ///
    /// This is a pure function with no side effects - same inputs always produce
    /// the same output, which is essential for deterministic order ID generation.
    ///
    /// # Implementation
    ///
    /// Uses AHasher for fast, high-quality hashing. While not cryptographically secure,
    /// it provides excellent distribution and collision resistance for this use case.
    fn hash_order_key(
        instrument_id: &str,
        side: OrderSide,
        price: Price,
        timestamp: UnixNanos,
        sequence: u64,
    ) -> u64 {
        let mut hasher = AHasher::default();

        // Hash all components that uniquely identify an order
        instrument_id.hash(&mut hasher);

        // Hash side as u8 for consistency
        (side as u8).hash(&mut hasher);

        // Hash price components directly
        price.raw.hash(&mut hasher);
        price.precision.hash(&mut hasher);

        // Hash timestamp
        timestamp.as_u64().hash(&mut hasher);

        // Hash sequence number
        sequence.hash(&mut hasher);

        hasher.finish()
    }
}

impl Default for SyntheticOrderIdGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_determinism() {
        // Same inputs must produce same ID
        let mut generator1 = SyntheticOrderIdGenerator::new();
        let mut generator2 = SyntheticOrderIdGenerator::new();

        let instrument = "BTCUSDT";
        let side = OrderSide::Buy;
        let price = Price::from("50000.00");
        let timestamp = UnixNanos::from(1700000000000000000);
        let sequence = 42;

        let id1 = generator1.generate_id(instrument, side, price, timestamp, sequence);
        let id2 = generator2.generate_id(instrument, side, price, timestamp, sequence);

        assert_eq!(id1, id2, "Same inputs must produce identical order IDs");
    }

    #[test]
    fn test_determinism_multiple_calls() {
        // Multiple calls with same inputs should produce same ID
        let mut generator = SyntheticOrderIdGenerator::new();

        let instrument = "ETHUSDT";
        let side = OrderSide::Sell;
        let price = Price::from("3000.50");
        let timestamp = UnixNanos::from(1700000000000000000);
        let sequence = 100;

        let id1 = generator.generate_id(instrument, side, price, timestamp, sequence);
        let id2 = generator.generate_id(instrument, side, price, timestamp, sequence);
        let id3 = generator.generate_id(instrument, side, price, timestamp, sequence);

        assert_eq!(id1, id2);
        assert_eq!(id2, id3);
    }

    #[test]
    fn test_uniqueness_by_price() {
        // Different prices should produce different IDs
        let mut generator = SyntheticOrderIdGenerator::new();

        let instrument = "BTCUSDT";
        let side = OrderSide::Buy;
        let timestamp = UnixNanos::from(1700000000000000000);
        let sequence = 42;

        let id1 = generator.generate_id(
            instrument,
            side,
            Price::from("50000.00"),
            timestamp,
            sequence,
        );
        let id2 = generator.generate_id(
            instrument,
            side,
            Price::from("50000.01"),
            timestamp,
            sequence,
        );
        let id3 = generator.generate_id(
            instrument,
            side,
            Price::from("51000.00"),
            timestamp,
            sequence,
        );

        assert_ne!(id1, id2, "Different prices must produce different IDs");
        assert_ne!(id1, id3, "Different prices must produce different IDs");
        assert_ne!(id2, id3, "Different prices must produce different IDs");
    }

    #[test]
    fn test_uniqueness_by_side() {
        // Different sides should produce different IDs
        let mut generator = SyntheticOrderIdGenerator::new();

        let instrument = "BTCUSDT";
        let price = Price::from("50000.00");
        let timestamp = UnixNanos::from(1700000000000000000);
        let sequence = 42;

        let id_buy = generator.generate_id(instrument, OrderSide::Buy, price, timestamp, sequence);
        let id_sell =
            generator.generate_id(instrument, OrderSide::Sell, price, timestamp, sequence);

        assert_ne!(
            id_buy, id_sell,
            "Different sides must produce different IDs"
        );
    }

    #[test]
    fn test_uniqueness_by_sequence() {
        // Different sequences should produce different IDs
        let mut generator = SyntheticOrderIdGenerator::new();

        let instrument = "BTCUSDT";
        let side = OrderSide::Buy;
        let price = Price::from("50000.00");
        let timestamp = UnixNanos::from(1700000000000000000);

        let id1 = generator.generate_id(instrument, side, price, timestamp, 42);
        let id2 = generator.generate_id(instrument, side, price, timestamp, 43);
        let id3 = generator.generate_id(instrument, side, price, timestamp, 100);

        assert_ne!(id1, id2, "Different sequences must produce different IDs");
        assert_ne!(id1, id3, "Different sequences must produce different IDs");
        assert_ne!(id2, id3, "Different sequences must produce different IDs");
    }

    #[test]
    fn test_uniqueness_by_timestamp() {
        // Different timestamps should produce different IDs
        let mut generator = SyntheticOrderIdGenerator::new();

        let instrument = "BTCUSDT";
        let side = OrderSide::Buy;
        let price = Price::from("50000.00");
        let sequence = 42;

        let id1 = generator.generate_id(
            instrument,
            side,
            price,
            UnixNanos::from(1700000000000000000),
            sequence,
        );
        let id2 = generator.generate_id(
            instrument,
            side,
            price,
            UnixNanos::from(1700000000000000001),
            sequence,
        );
        let id3 = generator.generate_id(
            instrument,
            side,
            price,
            UnixNanos::from(1700000001000000000),
            sequence,
        );

        assert_ne!(id1, id2, "Different timestamps must produce different IDs");
        assert_ne!(id1, id3, "Different timestamps must produce different IDs");
        assert_ne!(id2, id3, "Different timestamps must produce different IDs");
    }

    #[test]
    fn test_uniqueness_by_instrument() {
        // Different instruments should produce different IDs
        let mut generator = SyntheticOrderIdGenerator::new();

        let side = OrderSide::Buy;
        let price = Price::from("50000.00");
        let timestamp = UnixNanos::from(1700000000000000000);
        let sequence = 42;

        let id1 = generator.generate_id("BTCUSDT", side, price, timestamp, sequence);
        let id2 = generator.generate_id("ETHUSDT", side, price, timestamp, sequence);
        let id3 = generator.generate_id("SOLUSDT", side, price, timestamp, sequence);

        assert_ne!(id1, id2, "Different instruments must produce different IDs");
        assert_ne!(id1, id3, "Different instruments must produce different IDs");
        assert_ne!(id2, id3, "Different instruments must produce different IDs");
    }

    #[test]
    fn test_nautilus_integration() {
        // Generated IDs must be valid VenueOrderId instances
        let mut generator = SyntheticOrderIdGenerator::new();

        let id = generator.generate_id(
            "BTCUSDT",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        // Should be able to convert to string
        let id_str = id.to_string();
        assert!(
            !id_str.is_empty(),
            "Order ID should have string representation"
        );

        // Should start with L3 prefix
        assert!(
            id_str.starts_with("L3-"),
            "Synthetic order IDs should have L3- prefix"
        );

        // Should contain instrument identifier
        assert!(
            id_str.contains("BTCUSDT"),
            "Order ID should contain instrument identifier"
        );
    }

    #[test]
    fn test_id_format() {
        // Verify the format of generated IDs
        let mut generator = SyntheticOrderIdGenerator::new();

        let id = generator.generate_id(
            "BTCUSDT",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        let id_str = id.to_string();

        // Format should be: L3-{instrument_short}-{16_hex_chars}
        let parts: Vec<&str> = id_str.split('-').collect();
        assert_eq!(parts.len(), 3, "ID should have 3 parts separated by '-'");
        assert_eq!(parts[0], "L3", "First part should be 'L3'");
        assert_eq!(
            parts[1], "BTCUSDT",
            "Second part should be instrument (up to 8 chars)"
        );
        assert_eq!(parts[2].len(), 16, "Third part should be 16 hex characters");

        // Verify hex format
        assert!(
            parts[2].chars().all(|c| c.is_ascii_hexdigit()),
            "Hash should be valid hex"
        );
    }

    #[test]
    fn test_long_instrument_name() {
        // Test instrument names longer than 8 characters
        let mut generator = SyntheticOrderIdGenerator::new();

        let id = generator.generate_id(
            "VERYLONGINSTRUMENTNAME",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        let id_str = id.to_string();
        let parts: Vec<&str> = id_str.split('-').collect();

        // Instrument part should be truncated to 8 chars
        assert_eq!(
            parts[1].len(),
            8,
            "Instrument should be truncated to 8 characters"
        );
        assert_eq!(parts[1], "VERYLONG", "Should truncate to first 8 chars");
    }

    #[test]
    fn test_hash_consistency() {
        // Internal hash function should be consistent
        let hash1 = SyntheticOrderIdGenerator::hash_order_key(
            "BTCUSDT",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        let hash2 = SyntheticOrderIdGenerator::hash_order_key(
            "BTCUSDT",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        assert_eq!(hash1, hash2, "Hash function must be deterministic");
    }

    #[test]
    fn test_default_constructor() {
        // Test Default trait implementation
        let generator1 = SyntheticOrderIdGenerator::default();
        let generator2 = SyntheticOrderIdGenerator::new();

        // Both should produce same results
        let mut generator1 = generator1;
        let mut generator2 = generator2;

        let id1 = generator1.generate_id(
            "BTCUSDT",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        let id2 = generator2.generate_id(
            "BTCUSDT",
            OrderSide::Buy,
            Price::from("50000.00"),
            UnixNanos::from(1700000000000000000),
            42,
        );

        assert_eq!(id1, id2, "Default and new() should produce same results");
    }
}
